package com.example.budgettracker.ui.theme

import androidx.compose.ui.graphics.Color

// ---- Light theme roles (design §3.1) ----
val LightPrimary = Color(0xFF0D2736)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBEDCEC)
val LightOnPrimaryContainer = Color(0xFF001E2C)
val LightSecondary = Color(0xFF4B5C66)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCDDCE6)
val LightOnSecondaryContainer = Color(0xFF06151E)
val LightTertiary = Color(0xFFB07B3A)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDDB6)
val LightOnTertiaryContainer = Color(0xFF2A1700)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD4)
val LightOnErrorContainer = Color(0xFF410001)
val LightBackground = Color(0xFFF4F8FA)
val LightOnBackground = Color(0xFF0E141A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0E141A)
val LightSurfaceVariant = Color(0xFFE6ECEE)
val LightOnSurfaceVariant = Color(0xFF404951)
val LightOutline = Color(0xFF6F7E87)
val LightOutlineVariant = Color(0xFFC2CDD3)
val LightInverseSurface = Color(0xFF2B3238)
val LightInverseOnSurface = Color(0xFFEFF4F7)
val LightInversePrimary = Color(0xFF9CC8DE)
val LightScrim = Color(0xFF000000)
// Cool blue-gray surface-container ramp (lowest=lightest) so light surfaces stay neutral, not warm.
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF7FAFB)
val LightSurfaceContainer = Color(0xFFF1F5F7)
val LightSurfaceContainerHigh = Color(0xFFEBF0F2)
val LightSurfaceContainerHighest = Color(0xFFE6ECEE)
val LightSurfaceBright = Color(0xFFFFFFFF)
val LightSurfaceDim = Color(0xFFD9E1E5)

// ---- Dark theme roles (design §3.1, first-class) ----
val DarkPrimary = Color(0xFF9CC8DE)
val DarkOnPrimary = Color(0xFF003547)
val DarkPrimaryContainer = Color(0xFF143548)
val DarkOnPrimaryContainer = Color(0xFFC5E5F9)
val DarkSecondary = Color(0xFFB5C5CF)
val DarkOnSecondary = Color(0xFF20303A)
val DarkSecondaryContainer = Color(0xFF36464F)
val DarkOnSecondaryContainer = Color(0xFFD1E1EB)
val DarkTertiary = Color(0xFFFFB68D)
val DarkOnTertiary = Color(0xFF4A2700)
val DarkTertiaryContainer = Color(0xFF6A3B16)
val DarkOnTertiaryContainer = Color(0xFFFFDDB6)
val DarkError = Color(0xFFFFB4A8)
val DarkOnError = Color(0xFF690003)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD4)
val DarkBackground = Color(0xFF0A1218)
val DarkOnBackground = Color(0xFFE0E7EC)
val DarkSurface = Color(0xFF11191F)
val DarkOnSurface = Color(0xFFE0E7EC)
val DarkSurfaceVariant = Color(0xFF1A2229) // design "surface-2"
val DarkOnSurfaceVariant = Color(0xFFC0C9D0)
val DarkOutline = Color(0xFF7C8A93)
val DarkOutlineVariant = Color(0xFF3F484F)
val DarkInverseSurface = Color(0xFFE0E7EC)
val DarkInverseOnSurface = Color(0xFF2B3238)
val DarkInversePrimary = Color(0xFF0D2736)
val DarkScrim = Color(0xFF000000)
// Navy surface-container ramp (low→high = darker→lighter). M3's baseline defaults render brown in a
// navy scheme; these keep sheets/menus/cards navy. Mirrors the design bg / surface / surface-2/3.
val DarkSurfaceContainerLowest = Color(0xFF0A1218)
val DarkSurfaceContainerLow = Color(0xFF11191F)
val DarkSurfaceContainer = Color(0xFF151E25)
val DarkSurfaceContainerHigh = Color(0xFF1A2229)
val DarkSurfaceContainerHighest = Color(0xFF243038)
val DarkSurfaceBright = Color(0xFF243038)
val DarkSurfaceDim = Color(0xFF0A1218)

// ---- Semantic signal colors (fixed, never confused with brand chrome; §3.1) ----
val IncomeLight = Color(0xFF1F7A5A)
val IncomeDark = Color(0xFF74D9B5)
val OverageLight = Color(0xFFB3261E)
val OverageDark = Color(0xFFFFB4A8)
// `expense` is intentionally NOT a fixed hex — it uses the theme's onSurface (see Theme.kt).

// ---- Seed group colors (PRODUCT_SPEC §6.7): accent bars / 8dp dots only, never full backgrounds ----
val SeedIncome = Color(0xFF10B981)
val SeedBills = Color(0xFFEF4444)
val SeedHousehold = Color(0xFFF59E0B)
val SeedDebt = Color(0xFFDC2626)
val SeedLeisure = Color(0xFF8B5CF6)
val SeedSavings = Color(0xFF0EA5E9)
val SeedOther = Color(0xFF64748B)
